#**Gradient Descent**

In [ ]:
x_old = 2
y = 2 * x_old
l_rate = 0.1
x_new = x_old - (l_rate * y)
print(x_new)

1.6


In [ ]:
x_old = 2
y = 2 * x_old
l_rate = 0.01
for i in range(100):
    x_new = x_old - (l_rate * y)
    x_old = x_new
    y = 2*x_old
    print(x_new)

1.96
1.9208
1.882384
1.84473632
1.8078415936
1.771684761728
1.73625106649344
1.7015260451635712
1.6674955242602998
1.6341456137750938
1.601462701499592
1.5694334474696001
1.538044778520208
1.5072838829498039
1.4771382052908077
1.4475954411849916
1.4186435323612918
1.3902706617140659
1.3624652484797846
1.335215943510189
1.308511624639985
1.2823413921471853
1.2566945643042415
1.2315606730181567
1.2069294595577935
1.1827908703666377
1.159135052959305
1.135952351900119
1.1132333048621166
1.0909686387648743
1.0691492659895767
1.0477662806697852
1.0268109550563895
1.0062747359552617
0.9861492412361565
0.9664262564114334
0.9470977312832047
0.9281557766575407
0.9095926611243899
0.891400807901902
0.8735727917438639
0.8561013359089866
0.8389793091908069
0.8221997230069907
0.805755728546851
0.7896406139759139
0.7738478016963957
0.7583708456624677
0.7432034287492184
0.7283393601742341
0.7137725729707494
0.6994971215113344
0.6855071790811077
0.6717970354994856
0.6583610947894959
0.645193872893706
0

#**Scaler, Vector, Matrix, and Tensor**

In [ ]:
import numpy as np

weights = np.random.rand(3,3)
print(weights)

[[0.65802499 0.50460642 0.79868414]
 [0.48169602 0.62253978 0.77624631]
 [0.34747754 0.49915259 0.84388388]]


In [ ]:
np.random.seed(40)
weights = np.random.rand(3,3)
print(weights)

[[0.40768703 0.05536604 0.78853488]
 [0.28730518 0.45035059 0.30391231]
 [0.52639952 0.62381221 0.77677546]]


#**Adding two vectors using Tensorflow**

In [ ]:
import tensorflow as tf

# Define two vectors
vector1 = tf.constant([1.0, 2.0, 3.0], dtype = tf.float32)
vector2 = tf.constant([4.0, 5.0, 6.0], dtype = tf.float32)

# Add the vectors
result = tf.add(vector1, vector2)

# Print the result
print("Result:", result.numpy())


Result: [5. 7. 9.]


In [ ]:
# Set a random seed for reproducibility
np.random.seed(42)
# Generate random vectors
vector1 = tf.constant(np.random.rand(4624, 1), dtype=tf.float32)
vector2 = tf.constant(np.random.rand(4624, 1), dtype=tf.float32)
# Add the vectors
result = tf.add(vector1, vector2)
# Print the result
print("Vector1:")
print(vector1.numpy())
print("\nVector2:")
print(vector2.numpy())
print("\nResult:")
print(result.numpy())

Vector1:
[[0.37454012]
 [0.9507143 ]
 [0.7319939 ]
 ...
 [0.76465094]
 [0.1466951 ]
 [0.6903229 ]]

Vector2:
[[0.9450241 ]
 [0.6825405 ]
 [0.33161685]
 ...
 [0.9148862 ]
 [0.4891965 ]
 [0.4502652 ]]

Result:
[[1.3195642]
 [1.6332548]
 [1.0636108]
 ...
 [1.679537 ]
 [0.6358916]
 [1.140588 ]]
